### ISSUE TITLE
Multiples erreurs dans le plugin

### ISSUE THREAD

**Issue by bvanheu** [mlemelin/xbmc-illicowebtv#6]
Salut,

Le plugin throw plusieurs erreur "KeyError" lorsqu'il tente de parser le resultat de illico.tv.

Il semble qu'il existe une version 1.6.1, savez-vous ou se trouve le code?

**Comment by marseneault** [comment]
Tu peux trouver une version à jour et fonctionnelle sur mon github: https://github.com/marseneault/xbmc-illicowebtv

**Comment by bvanheu** [comment]
Cool merci!
